# Generated by Django 3.2 on 2022-12-22 11:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221221_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Недопустимое имя пользователя', regex='^[\\w.@+-]+$')], verbose_name='Username'),
        ),
    ]
